// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Mutation struct {
}

type Profile struct {
	ID            string          `json:"id"`
	Name          string          `json:"name"`
	BirthDate     *string         `json:"birthDate,omitempty"`
	IsUnborn      bool            `json:"isUnborn"`
	Relationships []*Relationship `json:"relationships"`
}

type Query struct {
}

type Relationship struct {
	ID    string   `json:"id"`
	From  *Profile `json:"from"`
	To    *Profile `json:"to"`
	Title string   `json:"title"`
}
